name: linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  js-linter:
    name: Javascript linter (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install standard modules
        run: yarn add standard
      - name: Run Standard
        run: yarn standard html/index.js
  html-linter:
    name: HTML linter (html5validator) 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: html/
  style-linter:
    name: CSS linter (stylelint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-hub/stylelint@master
        env:
        PATTERN: "html/*.css"
